#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

restore0Dir

runApplication blockMesh
runApplication topoSet
runApplication setsToZones -noFlipMap
runApplication setFields
runApplication decomposePar -no-libs
runParallel $(getApplication)

#------------------------------------------------------------------------------
