# W2-T4 analytic/sampled sphere CUDA primal job.
#
# Usage (on the registered Colab T4 runtime):
#   julia --project=<T4 env> scripts/waterlily_w2t4_job.jl \
#         <params.jl> <mode> <out_prefix>
#
# <params.jl> defines `W2T4_PARAMS` generated by the registered recorder from
# `docs/evidence/sdf_native_w2t4a_analytic_sphere_criteria_2026_09.json`; this
# job asserts every parameter against the committed implementation and refuses
# to run on drift.  <mode> is `analytic` (W2-T4a; the `gridsdf` mode is
# reserved for W2-T4b after W1g).  Writes `<out_prefix>.forces.csv`,
# `<out_prefix>.summary.json` and prints a delimited summary block.

using SHA
using CUDA

include(joinpath(@__DIR__, "..", "julia", "CFDSDFWaterLily", "src", "CFDSDFWaterLily.jl"))
using .CFDSDFWaterLily
using .CFDSDFWaterLily.GridSDFBody
using WaterLily

length(ARGS) == 3 || error("usage: waterlily_w2t4_job.jl <params.jl> <mode> <out_prefix>")
params_path, mode, out_prefix = ARGS
include(params_path)

function assert_registered(p)
    @assert Tuple(p.flow_dims) == CFDSDFWaterLily.FLOW_DIMS "flow_dims drift"
    @assert Tuple(Float64.(p.solver_center)) == CFDSDFWaterLily.SOLVER_CENTER "solver_center drift"
    @assert Float64(p.solver_radius) == CFDSDFWaterLily.SOLVER_RADIUS "solver_radius drift"
    @assert Float64(p.u_inf) == CFDSDFWaterLily.FREESTREAM "u_inf drift"
    @assert Float64(p.reynolds) == CFDSDFWaterLily.REYNOLDS "reynolds drift"
    @assert Float64(p.viscosity) == CFDSDFWaterLily.SOLVER_VISCOSITY "viscosity drift"
    @assert Tuple(Float64.(p.world_origin)) == CFDSDFWaterLily.WORLD_ORIGIN_M "world_origin drift"
    @assert Float64(p.world_per_solver) == CFDSDFWaterLily.WORLD_PER_SOLVER "world_per_solver drift"
    return nothing
end
assert_registered(W2T4_PARAMS)

function json_number(x)
    x isa Bool && return x ? "true" : "false"
    x isa Integer && return string(x)
    return string(Float64(x))
end
json_array(values) = "[" * join(json_number.(values), ",") * "]"

mean_of(rows, i) = sum(row[i] for row in rows) / length(rows)

function time_weighted_mean(rows, column, fallback)
    length(rows) >= 2 || return fallback
    numerator = 0.0
    denominator = 0.0
    for index in 1:(length(rows) - 1)
        dt = rows[index + 1][2] - rows[index][2]
        numerator += 0.5 * (rows[index][column] + rows[index + 1][column]) * dt
        denominator += dt
    end
    denominator > 0.0 ? numerator / denominator : fallback
end

function run_campaign(body; t_end, burn_in, sample_every)
    sim = CFDSDFWaterLily.build_sphere_sim(body; mem = CuArray)
    history = Vector{NTuple{7,Float64}}()
    warm_started = time()
    sim_step!(sim)  # compile kernels, excluded from the reported ms/step
    first_step_seconds = time() - warm_started
    step = 1
    peak_vram = CUDA.used_memory()
    started = time()
    while sim_time(sim) < t_end
        sim_step!(sim)
        step += 1
        if step % sample_every == 0
            fp = CFDSDFWaterLily.pressure_force_on_body(sim)
            fv = CFDSDFWaterLily.viscous_force_on_body(sim)
            push!(history, (
                Float64(step),
                Float64(sim_time(sim)),
                fp[1] + fv[1],
                fp[2] + fv[2],
                fp[3] + fv[3],
                fp[1],
                fv[1],
            ))
        end
        if step % 50 == 0
            peak_vram = max(peak_vram, CUDA.used_memory())
        end
    end
    wall_seconds = time() - started
    peak_vram = max(peak_vram, CUDA.used_memory())
    finite_u = all(isfinite, sim.flow.u)
    finite_p = all(isfinite, sim.flow.p)
    window = [row for row in history if row[2] >= burn_in && row[2] <= t_end]
    isempty(window) && error("empty measurement window")
    mid = 0.5 * (burn_in + t_end)
    first_half = [row for row in window if row[2] < mid]
    second_half = [row for row in window if row[2] >= mid]
    (isempty(first_half) || isempty(second_half)) && error("empty stationarity half-window")
    area = CFDSDFWaterLily.sphere_reference_area()
    mean_drag = mean_of(window, 3)
    time_weighted = (
        time_weighted_mean(window, 3, mean_drag),
        time_weighted_mean(window, 4, mean_of(window, 4)),
        time_weighted_mean(window, 5, mean_of(window, 5)),
    )
    return (
        history = history,
        steps = step,
        wall_seconds = wall_seconds,
        first_step_seconds = first_step_seconds,
        t_end_reached = Float64(sim_time(sim)),
        finite_u = finite_u,
        finite_p = finite_p,
        finite_forces = all(row -> all(isfinite, row), history),
        window_mean_drag = mean_drag,
        window_mean_lift = mean_of(window, 4),
        window_mean_side = mean_of(window, 5),
        time_weighted_mean_drag = time_weighted[1],
        time_weighted_mean_lift = time_weighted[2],
        time_weighted_mean_side = time_weighted[3],
        first_half_mean_drag = mean_of(first_half, 3),
        second_half_mean_drag = mean_of(second_half, 3),
        cd = mean_drag / (0.5 * CFDSDFWaterLily.FREESTREAM^2 * area),
        peak_vram_bytes = peak_vram,
    )
end

body = mode == "analytic" ? CFDSDFWaterLily.analytic_sphere_body() : error("mode $(mode) is not enabled before W1g")
fingerprint = CFDSDFWaterLily.runtime_fingerprint()
result = run_campaign(
    body;
    t_end = Float64(W2T4_PARAMS.t_end),
    burn_in = Float64(W2T4_PARAMS.burn_in),
    sample_every = Int(W2T4_PARAMS.sample_every),
)
vram_total = last(CUDA.memory_info())

csv_path = out_prefix * ".forces.csv"
open(csv_path, "w") do io
    println(io, "step,t_ud,drag,lift,side,pressure_drag,viscous_drag")
    for row in result.history
        println(io, join(row, ","))
    end
end
csv_sha256 = bytes2hex(sha256(read(csv_path)))

summary = string(
    "{",
    "\"mode\":\"", mode, "\",",
    "\"julia_version\":\"", fingerprint.julia_version, "\",",
    "\"julia_threads\":", fingerprint.julia_threads, ",",
    "\"waterlily_version\":\"", fingerprint.waterlily_version, "\",",
    "\"waterlily_backend\":\"", fingerprint.waterlily_backend, "\",",
    "\"cuda_jl_version\":\"", string(pkgversion(CUDA)), "\",",
    "\"gpu_name\":\"", CUDA.name(CUDA.device()), "\",",
    "\"t_end_target\":", json_number(W2T4_PARAMS.t_end), ",",
    "\"t_end_reached\":", json_number(result.t_end_reached), ",",
    "\"steps\":", result.steps, ",",
    "\"wall_seconds\":", json_number(result.wall_seconds), ",",
    "\"first_step_seconds\":", json_number(result.first_step_seconds), ",",
    "\"ms_per_step\":", json_number(1000 * result.wall_seconds / max(result.steps - 1, 1)), ",",
    "\"force_samples\":", length(result.history), ",",
    "\"finite_u\":", result.finite_u, ",",
    "\"finite_p\":", result.finite_p, ",",
    "\"finite_forces\":", result.finite_forces, ",",
    "\"window_mean_drag\":", json_number(result.window_mean_drag), ",",
    "\"window_mean_lift\":", json_number(result.window_mean_lift), ",",
    "\"window_mean_side\":", json_number(result.window_mean_side), ",",
    "\"time_weighted_mean_drag\":", json_number(result.time_weighted_mean_drag), ",",
    "\"time_weighted_mean_lift\":", json_number(result.time_weighted_mean_lift), ",",
    "\"time_weighted_mean_side\":", json_number(result.time_weighted_mean_side), ",",
    "\"first_half_mean_drag\":", json_number(result.first_half_mean_drag), ",",
    "\"second_half_mean_drag\":", json_number(result.second_half_mean_drag), ",",
    "\"cd\":", json_number(result.cd), ",",
    "\"peak_vram_bytes\":", result.peak_vram_bytes, ",",
    "\"vram_total_bytes\":", vram_total, ",",
    "\"csv_sha256\":\"", csv_sha256, "\",",
    "\"final_force\":", json_array((
        result.history[end][3], result.history[end][4], result.history[end][5],
        result.history[end][6], result.history[end][7],
    )),
    "}",
)
summary_path = out_prefix * ".summary.json"
write(summary_path, summary * "\n")

println("W2T4_SUMMARY_BEGIN")
println(summary)
println("W2T4_SUMMARY_END")
println("W2T4_JOB_DONE ", mode, " ", out_prefix)
