# W2a analytic/sampled sphere CPU primal job.
#
# Usage:
#   julia --threads=auto --project=<pkg> scripts/waterlily_w2a_job.jl \
#         <params.jl> <mode> <out_prefix>
#
# <params.jl> defines `W2A_PARAMS` generated by the registered runner from
# `docs/evidence/sdf_native_w2a_sphere_cpu_criteria_2026_09.json`; this job
# asserts every parameter against the committed implementation and refuses to
# run on drift.  <mode> is `analytic` or `gridsdf`.  Writes
# `<out_prefix>.forces.csv` and `<out_prefix>.summary.json`.

using SHA

include(joinpath(@__DIR__, "..", "julia", "CFDSDFWaterLily", "src", "CFDSDFWaterLily.jl"))
using .CFDSDFWaterLily
using .CFDSDFWaterLily.GridSDFBody
Base.include(CFDSDFWaterLily, joinpath(@__DIR__, "..", "julia", "CFDSDFWaterLily", "src", "WaterLilyNormalFloorBody.jl"))
Base.include(CFDSDFWaterLily, joinpath(@__DIR__, "..", "julia", "CFDSDFWaterLily", "src", "CandidateCWaterLilyBody.jl"))
using WaterLily

length(ARGS) == 3 || error("usage: waterlily_w2a_job.jl <params.jl> <mode> <out_prefix>")
params_path, mode, out_prefix = ARGS
include(params_path)

function assert_registered(p)
    @assert Tuple(p.flow_dims) == CFDSDFWaterLily.FLOW_DIMS "flow_dims drift"
    @assert Tuple(Float64.(p.solver_center)) == CFDSDFWaterLily.SOLVER_CENTER "solver_center drift"
    @assert Float64(p.solver_radius) == CFDSDFWaterLily.SOLVER_RADIUS "solver_radius drift"
    @assert Float64(p.u_inf) == CFDSDFWaterLily.FREESTREAM "u_inf drift"
    @assert Float64(p.reynolds) == CFDSDFWaterLily.REYNOLDS "reynolds drift"
    @assert Float64(p.viscosity) == CFDSDFWaterLily.SOLVER_VISCOSITY "viscosity drift"
    @assert Tuple(Float64.(p.phi_origin)) == CFDSDFWaterLily.SPHERE_PHI_ORIGIN "phi_origin drift"
    @assert Float64(p.phi_spacing) == CFDSDFWaterLily.SPHERE_PHI_SPACING "phi_spacing drift"
    @assert Tuple(p.phi_shape) == CFDSDFWaterLily.SPHERE_PHI_SHAPE "phi_shape drift"
    @assert Tuple(Float64.(p.phi_center)) == CFDSDFWaterLily.SPHERE_CENTER_M "phi_center drift"
    @assert Float64(p.phi_radius) == CFDSDFWaterLily.SPHERE_RADIUS_M "phi_radius drift"
    @assert Float64(p.outside_value) == CFDSDFWaterLily.OUTSIDE_VALUE_M "outside_value drift"
    @assert Float64(p.run_margin) == CFDSDFWaterLily.RUN_MARGIN_M "run_margin drift"
    @assert Tuple(Float64.(p.world_origin)) == CFDSDFWaterLily.WORLD_ORIGIN_M "world_origin drift"
    @assert Float64(p.world_per_solver) == CFDSDFWaterLily.WORLD_PER_SOLVER "world_per_solver drift"
    return nothing
end
assert_registered(W2A_PARAMS)

function json_number(x)
    x isa Bool && return x ? "true" : "false"
    x isa Integer && return string(x)
    return string(Float64(x))
end
json_nullable_number(x) = isnothing(x) ? "null" : json_number(x)
json_array(values) = "[" * join(json_number.(values), ",") * "]"

const RHO_KG_M3 = 1.0
const U_REF_M_S = 1.0
const H_M = 0.0625
const FORCE_N_PER_SOLVER = RHO_KG_M3 * U_REF_M_S^2 * H_M^2
const MASS_KG_S_PER_SOLVER_VELOCITY = RHO_KG_M3 * U_REF_M_S * H_M^2

function boundary_mass_flow_kg_s(sim)
    u = sim.flow.u
    nx, ny, nz = size(u)[1:3]
    ys, zs = 2:ny-1, 2:nz-1
    xs = 2:nx-1
    # WaterLily BC! writes normal velocity on x=2/x=end and analogous faces.
    qin = -sum(Float64, @view u[2, ys, zs, 1]) * MASS_KG_S_PER_SOLVER_VELOCITY
    qout = sum(Float64, @view u[nx, ys, zs, 1]) * MASS_KG_S_PER_SOLVER_VELOCITY
    yminus = -sum(Float64, @view u[xs, 2, zs, 2]) * MASS_KG_S_PER_SOLVER_VELOCITY
    yplus = sum(Float64, @view u[xs, ny, zs, 2]) * MASS_KG_S_PER_SOLVER_VELOCITY
    zminus = -sum(Float64, @view u[xs, ys, 2, 3]) * MASS_KG_S_PER_SOLVER_VELOCITY
    zplus = sum(Float64, @view u[xs, ys, nz, 3]) * MASS_KG_S_PER_SOLVER_VELOCITY
    # This global divergence integral is diagnostic; immersed-boundary cells
    # prevent interpreting it alone as a conservation qualification.
    divergence_solver = 0.0
    for I in WaterLily.inside(sim.flow.p)
        divergence_solver += Float64(WaterLily.div(I, u))
    end
    divergence_kg_s = divergence_solver * MASS_KG_S_PER_SOLVER_VELOCITY
    return (inlet_kg_s=qin, outlet_kg_s=qout, yminus_kg_s=yminus,
            yplus_kg_s=yplus, zminus_kg_s=zminus, zplus_kg_s=zplus,
            net_outward_kg_s=qin+qout+yminus+yplus+zminus+zplus,
            integrated_divergence_kg_s=divergence_kg_s,
            divergence_boundary_difference_kg_s=divergence_kg_s-(qin+qout+yminus+yplus+zminus+zplus))
end

function exact_window_mean(samples, field::Symbol, t0, t1)
    length(samples) >= 2 || error("insufficient force samples for window")
    samples[1].t_ud <= t0 <= samples[end].t_ud || error("start of force window is unbracketed")
    samples[1].t_ud <= t1 <= samples[end].t_ud || error("end of force window is unbracketed")
    function value_at(target)
        index = findfirst(i -> samples[i].t_ud <= target <= samples[i+1].t_ud, 1:length(samples)-1)
        index === nothing && error("missing endpoint bracket at t=$target")
        a, b = samples[index], samples[index+1]
        weight = (target - a.t_ud) / (b.t_ud - a.t_ud)
        return getproperty(a, field) + weight * (getproperty(b, field) - getproperty(a, field))
    end
    interior = [sample for sample in samples if t0 < sample.t_ud < t1]
    times = vcat(Float64(t0), [sample.t_ud for sample in interior], Float64(t1))
    values = vcat(value_at(t0), [getproperty(sample, field) for sample in interior], value_at(t1))
    integral = 0.0
    for i in 1:length(times)-1
        integral += (times[i+1] - times[i]) * (values[i] + values[i+1]) / 2
    end
    return integral / (t1 - t0), length(interior)
end

function write_sample(io, row)
    println(io, join((row.step,row.t_ud,row.drag,row.lift,row.side,row.pressure_drag,
        row.viscous_drag,row.fx_n,row.fy_n,row.fz_n,row.inlet_kg_s,row.outlet_kg_s,
        row.yminus_kg_s,row.yplus_kg_s,row.zminus_kg_s,row.zplus_kg_s,
        row.net_outward_kg_s,row.integrated_divergence_kg_s,
        row.divergence_boundary_difference_kg_s), ","))
    flush(io)
    all(isfinite, values(row)) || error("non-finite force or physical boundary-flow sample at step=$(row.step)")
end

function run_campaign(body; t_end, burn_in, sample_every, history_io)
    sim = CFDSDFWaterLily.build_sphere_sim(body)
    history = Vector{NamedTuple}()
    warm_started = time()
    sim_step!(sim)  # compile kernels, excluded from the reported ms/step
    first_step_seconds = time() - warm_started
    step = 1
    started = time()
    while sim_time(sim) < t_end
        sim_step!(sim)
        step += 1
        if step % sample_every == 0 || sim_time(sim) >= t_end
            fp = CFDSDFWaterLily.pressure_force_on_body(sim)
            fv = CFDSDFWaterLily.viscous_force_on_body(sim)
            force = fp .+ fv
            flux = boundary_mass_flow_kg_s(sim)
            row = (; step=Float64(step), t_ud=Float64(sim_time(sim)),
                drag=force[1], lift=force[2], side=force[3],
                pressure_drag=fp[1], viscous_drag=fv[1],
                fx_n=force[1]*FORCE_N_PER_SOLVER,
                fy_n=force[2]*FORCE_N_PER_SOLVER,
                fz_n=force[3]*FORCE_N_PER_SOLVER,
                flux...)
            push!(history, row)
            write_sample(history_io, row)
        end
    end
    wall_seconds = time() - started
    finite_u = all(isfinite, sim.flow.u)
    finite_p = all(isfinite, sim.flow.p)
    mid = 0.5 * (burn_in + t_end)
    window_drag, window_count = exact_window_mean(history, :drag, burn_in, t_end)
    first_half_drag, _ = exact_window_mean(history, :drag, burn_in, mid)
    second_half_drag, _ = exact_window_mean(history, :drag, mid, t_end)
    window_lift, _ = exact_window_mean(history, :lift, burn_in, t_end)
    window_side, _ = exact_window_mean(history, :side, burn_in, t_end)
    flux_window = (;
        inlet_kg_s=first(exact_window_mean(history, :inlet_kg_s, burn_in, t_end)),
        outlet_kg_s=first(exact_window_mean(history, :outlet_kg_s, burn_in, t_end)),
        yminus_kg_s=first(exact_window_mean(history, :yminus_kg_s, burn_in, t_end)),
        yplus_kg_s=first(exact_window_mean(history, :yplus_kg_s, burn_in, t_end)),
        zminus_kg_s=first(exact_window_mean(history, :zminus_kg_s, burn_in, t_end)),
        zplus_kg_s=first(exact_window_mean(history, :zplus_kg_s, burn_in, t_end)),
        net_outward_kg_s=first(exact_window_mean(history, :net_outward_kg_s, burn_in, t_end)),
        integrated_divergence_kg_s=first(exact_window_mean(history, :integrated_divergence_kg_s, burn_in, t_end)),
        divergence_boundary_difference_kg_s=first(exact_window_mean(history, :divergence_boundary_difference_kg_s, burn_in, t_end)),
    )
    area = CFDSDFWaterLily.sphere_reference_area()
    mean_drag = window_drag
    return (
        history = history,
        steps = step,
        wall_seconds = wall_seconds,
        first_step_seconds = first_step_seconds,
        t_end_reached = Float64(sim_time(sim)),
        finite_u = finite_u,
        finite_p = finite_p,
        finite_forces = all(row -> all(isfinite, row), history),
        window_mean_drag = mean_drag,
        window_mean_lift = window_lift,
        window_mean_side = window_side,
        window_force_samples = window_count,
        first_half_mean_drag = first_half_drag,
        second_half_mean_drag = second_half_drag,
        cd = mean_drag / (0.5 * CFDSDFWaterLily.FREESTREAM^2 * area),
        mass_flow_window = flux_window,
    )
end

phi_margin_m = nothing
phi_sha256 = ""
body_mode = mode == "preflight_candidate_c" ? "candidate_c" : mode
body = if body_mode == "analytic"
    CFDSDFWaterLily.analytic_sphere_body()
elseif body_mode in ("grid_upstream", "candidate_c")
    grid = CFDSDFWaterLily.sphere_phi_fixture()
    phi_margin_m = zero_level_margin_m(grid.phi, grid.origin, grid.h)
    phi_sha256 = bytes2hex(sha256(reinterpret(UInt8, vec(grid.phi))))
    @assert phi_margin_m >= Float64(W2A_PARAMS.run_margin) "sampled sphere margin below registered three-spacing gate"
    base = CFDSDFWaterLily.NormalFloorWaterLilyBody(
        grid, CFDSDFWaterLily.WORLD_ORIGIN_M,
        Float64(CFDSDFWaterLily.WORLD_PER_SOLVER), 0.25)
    body_mode == "candidate_c" ? CFDSDFWaterLily.CandidateCWaterLilyBody(base) : base
else
    error("unknown mode $(mode)")
end

if mode == "preflight_candidate_c"
    sim = CFDSDFWaterLily.build_sphere_sim(body)
    flux = boundary_mass_flow_kg_s(sim)
    @assert all(isfinite, sim.flow.u) && all(isfinite, sim.flow.p)
    @assert all(isfinite, values(flux))
    println("W2A_C_INITIALIZATION_PREFLIGHT_PASS ", json_number(flux.net_outward_kg_s))
    exit(0)
end

fingerprint = CFDSDFWaterLily.runtime_fingerprint()
csv_path = out_prefix * ".forces.csv"
ispath(csv_path) && error("refusing to overwrite existing force history: $csv_path")
history_io = open(csv_path, "w")
println(history_io, "step,t_ud,drag_solver,lift_solver,side_solver,pressure_drag_solver,viscous_drag_solver,fx_n,fy_n,fz_n,inlet_kg_s,outlet_kg_s,yminus_kg_s,yplus_kg_s,zminus_kg_s,zplus_kg_s,net_outward_kg_s,integrated_divergence_kg_s,divergence_boundary_difference_kg_s")
flush(history_io)
result = run_campaign(
    body;
    t_end = Float64(W2A_PARAMS.t_end),
    burn_in = Float64(W2A_PARAMS.burn_in),
    sample_every = Int(W2A_PARAMS.sample_every),
    history_io = history_io,
)
close(history_io)

summary = string(
    "{",
    "\"mode\":\"", mode, "\",",
    "\"julia_version\":\"", fingerprint.julia_version, "\",",
    "\"julia_threads\":", fingerprint.julia_threads, ",",
    "\"waterlily_version\":\"", fingerprint.waterlily_version, "\",",
    "\"waterlily_backend\":\"", fingerprint.waterlily_backend, "\",",
    "\"blas_threads\":", fingerprint.blas_threads, ",",
    "\"t_end_target\":", json_number(W2A_PARAMS.t_end), ",",
    "\"t_end_reached\":", json_number(result.t_end_reached), ",",
    "\"steps\":", result.steps, ",",
    "\"wall_seconds\":", json_number(result.wall_seconds), ",",
    "\"first_step_seconds\":", json_number(result.first_step_seconds), ",",
    "\"ms_per_step\":", json_number(1000 * result.wall_seconds / max(result.steps - 1, 1)), ",",
    "\"force_samples\":", length(result.history), ",",
    "\"window_force_samples\":", result.window_force_samples, ",",
    "\"finite_u\":", result.finite_u, ",",
    "\"finite_p\":", result.finite_p, ",",
    "\"finite_forces\":", result.finite_forces, ",",
    "\"phi_margin_m\":", json_nullable_number(phi_margin_m), ",",
    "\"phi_sha256\":\"", phi_sha256, "\",",
    "\"world_origin_m\":", json_array(CFDSDFWaterLily.WORLD_ORIGIN_M), ",",
    "\"world_per_solver\":", json_number(CFDSDFWaterLily.WORLD_PER_SOLVER), ",",
    "\"window_mean_drag\":", json_number(result.window_mean_drag), ",",
    "\"window_mean_lift\":", json_number(result.window_mean_lift), ",",
    "\"window_mean_side\":", json_number(result.window_mean_side), ",",
    "\"first_half_mean_drag\":", json_number(result.first_half_mean_drag), ",",
    "\"second_half_mean_drag\":", json_number(result.second_half_mean_drag), ",",
    "\"cd\":", json_number(result.cd), ",",
    "\"mass_flow_window_kg_s\":{",
    "\"inlet\":", json_number(result.mass_flow_window.inlet_kg_s), ",",
    "\"outlet\":", json_number(result.mass_flow_window.outlet_kg_s), ",",
    "\"yminus\":", json_number(result.mass_flow_window.yminus_kg_s), ",",
    "\"yplus\":", json_number(result.mass_flow_window.yplus_kg_s), ",",
    "\"zminus\":", json_number(result.mass_flow_window.zminus_kg_s), ",",
    "\"zplus\":", json_number(result.mass_flow_window.zplus_kg_s), ",",
    "\"net_outward\":", json_number(result.mass_flow_window.net_outward_kg_s), ",",
    "\"integrated_divergence\":", json_number(result.mass_flow_window.integrated_divergence_kg_s),
    ",\"divergence_boundary_difference\":", json_number(result.mass_flow_window.divergence_boundary_difference_kg_s),
    "},",
    "\"final_force\":", json_array((
        result.history[end].drag, result.history[end].lift, result.history[end].side,
        result.history[end].pressure_drag, result.history[end].viscous_drag,
    )),
    "}",
)
summary_path = out_prefix * ".summary.json"
write(summary_path, summary * "\n")

println("W2A_JOB_DONE ", mode, " ", summary_path)
println(summary)
